# Generated by Django 3.2.6 on 2021-08-24 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meetups', '0006_auto_20210823_1013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meetup',
            old_name='organize_email',
            new_name='organizer_email',
        ),
    ]
